trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      pip install azure-storage-blob
      pip install phe
    displayName: 'Install dependencies'

  - script: |
      python app1.py  # Replace 'script.py' with the name of your Python script file
    displayName: 'Run Python script'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'home2'  # Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Upload encrypted content to Azure Blob Storage container
        az storage blob upload --data output.txt --container-name con1 --name output.txt --account-name azstore116
    displayName: 'Upload Encrypted Content to Azure Storage Container'
