trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    # Install dependencies
    pip install azure-storage-blob
    pip install phe
    # Run Python script
    python app.py
  displayName: 'Run Python Script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'home2'  # Azure service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Upload output.txt to Azure Storage container
      az storage blob upload --file output.txt --container-name con1 --name output.txt --account-name azstore116
  displayName: 'Upload Output File to Azure Storage Container'
